spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  mvc.log-request-details: true
  graphql:
    graphiql:
      enabled: true
server:
  error:
    include-stacktrace: always
    include-message: always
logging:
  level:
    web: debug
    org.springframework.security: debug